<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260407121044 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, location VARCHAR(255) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, create_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, max_attendees INT NOT NULL, is_active BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, organizer_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_911533C8876C4DDA ON conference (organizer_id)');
        $this->addSql('CREATE TABLE registration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, registration_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, ticket_type VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE registration_user (registration_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (registration_id, user_id))');
        $this->addSql('CREATE INDEX IDX_42ADC195833D8F43 ON registration_user (registration_id)');
        $this->addSql('CREATE INDEX IDX_42ADC195A76ED395 ON registration_user (user_id)');
        $this->addSql('CREATE TABLE registration_conference (registration_id INT NOT NULL, conference_id INT NOT NULL, PRIMARY KEY (registration_id, conference_id))');
        $this->addSql('CREATE INDEX IDX_AC2EFAE1833D8F43 ON registration_conference (registration_id)');
        $this->addSql('CREATE INDEX IDX_AC2EFAE1604B8382 ON registration_conference (conference_id)');
        $this->addSql('CREATE TABLE room (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, capacity INT NOT NULL, building VARCHAR(255) NOT NULL, floor VARCHAR(50) NOT NULL, equipment VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE room_venue (room_id INT NOT NULL, venue_id INT NOT NULL, PRIMARY KEY (room_id, venue_id))');
        $this->addSql('CREATE INDEX IDX_DB2DBAA654177093 ON room_venue (room_id)');
        $this->addSql('CREATE INDEX IDX_DB2DBAA640A73EBA ON room_venue (venue_id)');
        $this->addSql('CREATE TABLE session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, max_attendees INT NOT NULL, session_type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, track VARCHAR(100) DEFAULT NULL, capacity INT DEFAULT NULL, conference_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D044D5D4604B8382 ON session (conference_id)');
        $this->addSql('CREATE TABLE session_speaker (session_id INT NOT NULL, speaker_id INT NOT NULL, PRIMARY KEY (session_id, speaker_id))');
        $this->addSql('CREATE INDEX IDX_695D593B613FECDF ON session_speaker (session_id)');
        $this->addSql('CREATE INDEX IDX_695D593BD04A0F27 ON session_speaker (speaker_id)');
        $this->addSql('CREATE TABLE session_room (session_id INT NOT NULL, room_id INT NOT NULL, PRIMARY KEY (session_id, room_id))');
        $this->addSql('CREATE INDEX IDX_B4EE51B1613FECDF ON session_room (session_id)');
        $this->addSql('CREATE INDEX IDX_B4EE51B154177093 ON session_room (room_id)');
        $this->addSql('CREATE TABLE speaker (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, job_title VARCHAR(255) DEFAULT NULL, bio TEXT DEFAULT NULL, expertise VARCHAR(255) DEFAULT NULL, photo VARCHAR(100) DEFAULT NULL, social_links TEXT DEFAULT NULL, usser_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7B85DB61D840794C ON speaker (usser_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(100) DEFAULT NULL, role VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE venue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, city VARCHAR(255) DEFAULT NULL, state VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(50) DEFAULT NULL, capacity INT DEFAULT NULL, facilities VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE conference ADD CONSTRAINT FK_911533C8876C4DDA FOREIGN KEY (organizer_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE registration_user ADD CONSTRAINT FK_42ADC195833D8F43 FOREIGN KEY (registration_id) REFERENCES registration (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE registration_user ADD CONSTRAINT FK_42ADC195A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE registration_conference ADD CONSTRAINT FK_AC2EFAE1833D8F43 FOREIGN KEY (registration_id) REFERENCES registration (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE registration_conference ADD CONSTRAINT FK_AC2EFAE1604B8382 FOREIGN KEY (conference_id) REFERENCES conference (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE room_venue ADD CONSTRAINT FK_DB2DBAA654177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE room_venue ADD CONSTRAINT FK_DB2DBAA640A73EBA FOREIGN KEY (venue_id) REFERENCES venue (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D4604B8382 FOREIGN KEY (conference_id) REFERENCES conference (id)');
        $this->addSql('ALTER TABLE session_speaker ADD CONSTRAINT FK_695D593B613FECDF FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE session_speaker ADD CONSTRAINT FK_695D593BD04A0F27 FOREIGN KEY (speaker_id) REFERENCES speaker (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE session_room ADD CONSTRAINT FK_B4EE51B1613FECDF FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE session_room ADD CONSTRAINT FK_B4EE51B154177093 FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE speaker ADD CONSTRAINT FK_7B85DB61D840794C FOREIGN KEY (usser_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conference DROP CONSTRAINT FK_911533C8876C4DDA');
        $this->addSql('ALTER TABLE registration_user DROP CONSTRAINT FK_42ADC195833D8F43');
        $this->addSql('ALTER TABLE registration_user DROP CONSTRAINT FK_42ADC195A76ED395');
        $this->addSql('ALTER TABLE registration_conference DROP CONSTRAINT FK_AC2EFAE1833D8F43');
        $this->addSql('ALTER TABLE registration_conference DROP CONSTRAINT FK_AC2EFAE1604B8382');
        $this->addSql('ALTER TABLE room_venue DROP CONSTRAINT FK_DB2DBAA654177093');
        $this->addSql('ALTER TABLE room_venue DROP CONSTRAINT FK_DB2DBAA640A73EBA');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT FK_D044D5D4604B8382');
        $this->addSql('ALTER TABLE session_speaker DROP CONSTRAINT FK_695D593B613FECDF');
        $this->addSql('ALTER TABLE session_speaker DROP CONSTRAINT FK_695D593BD04A0F27');
        $this->addSql('ALTER TABLE session_room DROP CONSTRAINT FK_B4EE51B1613FECDF');
        $this->addSql('ALTER TABLE session_room DROP CONSTRAINT FK_B4EE51B154177093');
        $this->addSql('ALTER TABLE speaker DROP CONSTRAINT FK_7B85DB61D840794C');
        $this->addSql('DROP TABLE conference');
        $this->addSql('DROP TABLE registration');
        $this->addSql('DROP TABLE registration_user');
        $this->addSql('DROP TABLE registration_conference');
        $this->addSql('DROP TABLE room');
        $this->addSql('DROP TABLE room_venue');
        $this->addSql('DROP TABLE session');
        $this->addSql('DROP TABLE session_speaker');
        $this->addSql('DROP TABLE session_room');
        $this->addSql('DROP TABLE speaker');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE venue');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
